### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/cliente/10 HTTP/1.1
### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
Content-Type: application/json

{
  "nome": "Roberto",
  "cpf": "01923874656",
  "telefone": "49991751999"
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/2 HTTP/1.1
Content-Type: application/json

{
  "nome": "Roberto Atualizado",
  "cpf": "01923874656",
  "telefone": "49990000000"
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/3 HTTP/1.1